<script src="{{ url_for(theme.js) }}/scrollspy.js?v={{ version }}"></script>
<script src="{{ url_for(theme.js) }}/post-details.js?v={{ version }}"></script>

<!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-141257985-1"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-141257985-1');
</script>